[server]
server_name = localhost
port = 80
root = ./oxer-html
error = 404:/errors/404.html
error = 564:/errors/404.html
error = 500:/errors/404.html
error = 300:/errors/404.html

[location]
name = /
root = /
index = index.html
